baseURL = "https://labs.debruyn.dev/"
languageCode = "en-us"
title = "Data Engineer 101"
theme = "hugo-cards"

[params]
  description = "A list of useful websites and tools for (aspiring) data engineers"

  [params.copyright]
     name = "Sam Debruyn"
     link = "https://debruyn.dev"
