baseURL = "https://labs.debruyn.dev/"
languageCode = "en-us"
title = "Sam Debruyn Labs"
theme = "hugo-cards"

[params]
  builtBy = "Sam Debruyn"

  [params.copyright]
     name = "Sam Debruyn"
     link = "https://debruyn.dev"
