version: '3'
services:
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server_config/nginx:/etc/nginx/conf.d
      - ./server_config/certbot/conf:/etc/letsencrypt
      - ./server_config/certbot/www:/var/www/certbot
      - ./public:/var/www/public
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  certbot:
    image: certbot/certbot:arm64v8-latest
    restart: unless-stopped
    volumes:
      - ./server_config/certbot/conf:/etc/letsencrypt
      - ./server_config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"